### ISSUE TITLE
Sessionlock breaks "dropAll" ?

### ISSUE THREAD

**Issue by TheBestPessimist** [blagerweij/liquibase-sessionlock#18] opened 2022-08-10 13:24 UTC
I have a spring boot project (2.7.1) with liquibase (4.15.0) and sessionlock (1.5.3).

i use postgres in docker for my tests.

i have the following extra properties:

```properties
spring.jpa.hibernate.ddl-auto=none
spring.liquibase.drop-first=true
spring.liquibase.clear-checksums=true
```

The issue is that drop-first no longer works as expected because the table `databasechangelog` does not get dropped, but all other tables are => whenever i start a new test suite no migrations are run as liquibase believes all is set up.

How to repro:
- add sessionLock dependency
- add a few tables via liquibase migrations
- set the properties above
- run gradle clean test multiple times

After the second run, all tests fail and only the table `databasechangelog`  remains.
After i remove sessionLock, everything works as expected.

Is it possible that sessionLock breaks something for `drop-fist`/`dropAll` ?

**Comment by blagerweij** [comment] 2022-09-08 23:55
@TheBestPessimist I've tried your test-case, but it seems the problem is with using drop-first in integration tests, not with the sessionlock library. When using drop-first (even without the sessionlock extension), then integration tests will start to fail. Could you re-run your test without the sessionlock library, but with 'drop-first' set to true?

**Comment by TheBestPessimist** [comment] 2022-09-09 04:51
I am running my tests like that since the time i created the bug and they work:
![image](https://user-images.githubusercontent.com/4482210/189274261-bdf97dc1-e94d-4acd-b699-75f2fd65cedf.png)

**Comment by blagerweij** [comment] 2022-09-09 14:02
@TheBestPessimist I was able to reproduce the issue, and I think it's fixed in 1.6.0. Please give it a try and let me know the results. It appears to have been an issue where Postgres runs DDL statements in a transaction, and the StandardLockService used to have a 'database.commit();', but the SessionLockService did not have this.

**Comment by TheBestPessimist** [comment] 2022-09-09 14:07
Will try on Monday and keep u posted

**Comment by TheBestPessimist** [comment] 2022-09-12 10:41
from some short testing, 1.6.0 seems to work!

Thank you for the bugfix

**Comment by blagerweij** [comment] 2022-09-12 10:57
Nice! One small downside: the previous version used a class which extended from StandardLockService, so in the future if there's a breaking change in the Liquibase API for LockService, we'll need to update this class too.  I'll close the issue.

**Closed by blagerweij** 2022-09-12 10:57 UTC
